#!/bin/bash
robot_name="${HOSTNAME//-b1}"

if [ "$USER" != "robot" ]; then
	echo 'FATAL: CAN ONLY BE EXECUTED AS "robot" USER'
	exit
fi

if [ "$HOSTNAME" != "$robot_name-b1" ]; then
	echo "FATAL: CAN ONLY BE EXECUTED ON BASE PC"
	exit
fi

#retrieve client_list variables
source /u/robot/git/setup_cob4/helper_client_list.sh

echo "Executing adduser"
sudo /usr/sbin/adduser $1 --home /u/$1
sudo adduser $1 dialout
sudo adduser $1 cdrom
sudo adduser $1 floppy
sudo adduser $1 audio
sudo adduser $1 video
sudo adduser $1 plugdev
sudo adduser $1 users

echo "Syncing passwd file to other cob-pcs"
for i in $client_list_ip
do
	echo "sync passwd on $i"
	sudo rsync -e ssh -avz /etc/passwd /etc/shadow /etc/group root@$i:/etc/
done

if [ "$1" != "" ]; then
	echo "setup bash environment"
	sudo cp /u/robot/git/setup_cob4/cob-pcs/user.bashrc /u/$1/.bashrc
	if [ $(lsb_release -sc) == "trusty" ]; then
		sudo cp /u/robot/git/setup_cob4/cob-pcs/tmux.conf.trusty /u/$1/.tmux.conf
		sudo chown $1:$1 /u/$1/.tmux.conf	
	elif [ $(lsb_release -sc) == "xenial" ]; then
		sudo cp /u/robot/git/setup_cob4/cob-pcs/tmux.conf.xenial /u/$1/.tmux.conf
		sudo chown $1:$1 /u/$1/.tmux.conf
	else
		echo -e "\n${red}FATAL: Script only supports indigo and kinetic"
		exit
	fi
	
	sudo sed -i "s/myrobot/$robot_name/g" /u/$1/.bashrc
	sudo sed -i "s/mydistro/$ROS_DISTRO/g" /u/$1/.bashrc

	if [ ! -f /u/$1/.ssh/id_rsa ]; then
		echo "create new ssh key"
		sudo -u $1 ssh-keygen -f /u/$1/.ssh/id_rsa
	fi
	sudo -u $1 cat /u/$1/.ssh/id_rsa.pub | ssh $1@$robot_name-b1 "cat >> /u/$1/.ssh/authorized_keys"
	echo "login to $1@localhost"
	sudo -u $1 ssh $1@localhost 'exit'

	# login to all pcs using ip
	for i in $client_list_ip
	do
		echo "login to $1@$i"
		sudo -u $1 ssh $1@$i 'exit'
	done

	# login to all pcs using hostname
	for i in $client_list_hostnames
	do
		echo "login to $1@$i"
		sudo -u $1 ssh $1@$i 'exit'
	done

	if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then
		sudo su -c "rosdep init"
	fi
	sudo su -c "rosdep update" $1
	sudo su -c "mkdir -p ~/git/care-o-bot" $1
fi

echo "done adding user"
