#!/bin/bash
robot_name="${HOSTNAME//-b1}"

if [ "$USER" != "robot" ]; then 
	echo 'FATAL: CAN ONLY BE EXECUTED AS "robot" USER'
	exit
fi

if [ "$HOSTNAME" != "$robot_name-b1" ]; then 
	echo "FATAL: CAN ONLY BE EXECUTED ON BASE PC"
	exit
fi

IP=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
client_list=$(nmap --unprivileged $IP-50 --system-dns | grep report | awk '{print $6}' | sed 's/(//g;s/)//g' | tr '\n' ' ') 

echo "Executing adduser"
sudo /usr/sbin/adduser $1 --home /u/$1
sudo adduser $1 dialout 
sudo adduser $1 cdrom 
sudo adduser $1 floppy 
sudo adduser $1 audio
sudo adduser $1 video
sudo adduser $1 plugdev
sudo adduser $1 users 

echo "Syncing passwd file to other cob-pcs"
for i in $client_list
do
	echo "sync passwd on $i"
	sudo rsync -e ssh -avz /etc/passwd /etc/shadow /etc/group root@$i:/etc/
done

if [ "$1" != "" ]; then
	echo "setup bash environment"
	sudo cp /u/robot/git/setup_cob4/cob-pcs/user.bashrc /u/$1/.bashrc
	sudo sed -i "s/myrobot/$robot_name/g" /u/$1/.bashrc
	sudo sed -i "s/mydistro/$ROS_DISTRO/g" /u/$1/.bashrc

	if [ ! -f /u/$1/.ssh/id_rsa ]; then
		echo "create new ssh key"
		sudo -u $1 ssh-keygen -f /u/$1/.ssh/id_rsa
	fi
	sudo -u $1 cat /u/$1/.ssh/id_rsa.pub | ssh $1@$robot_name-b1 "cat >> /u/$1/.ssh/authorized_keys"
	echo "login to $1@localhost"
	sudo -u $1 ssh $1@localhost 'exit'
	for i in $client_list
	do
	    echo "login to $1@$i"
		sudo -u $1 ssh $1@$i 'exit'
	done

	if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then
		sudo su -c "rosdep init"
	fi
	sudo su -c "rosdep update" $1
	sudo su -c "mkdir -p ~/git/care-o-bot" $1
fi

echo "done adding user"
