#!/bin/bash
rm -rf /tmp/runningVMS
su mimic -c "ssh myrobot-h1 'vboxmanage list runningvms'" > /tmp/runningVMS

if grep -q myrobot-win "/tmp/runningVMS"; then
  echo "VM already running"
else
  echo "starting VM..."
  su mimic -c "ssh myrobot-h1 'export DISPLAY=:0 && virtualbox --startvm myrobot-win --fullscreen'"&
fi