#!/bin/bash
ROBOT=myrobotname
DISTRO=mydistro
USER=myuser

if (ssh $USER@$ROBOT-t2 "tmux has-session -t 'sm' 2> /dev/null"); then
  echo "Attempting to stop statemachine"
  logger -p user.info "Attempting to stop statemachine"
  ssh $USER@$ROBOT-t2 "tmux send -t sm C-c"
  sleep 5
  ssh $USER@$ROBOT-t2 "tmux kill-session -t sm"
fi
if (su $USER -l -c "tmux has-session -t 'bringup' 2> /dev/null"); then
  echo "Attempting to stop bringup"
  logger -p user.info "Attempting to stop bringup"
  su $USER -l -c "tmux send -t bringup C-c"
  PID=$(cat /tmp/robot.launch.pid)
  while [ -e /proc/$PID ]; do echo "still waiting for bringup to stop" && sleep 1; done
  su $USER -l -c "tmux kill-session -t bringup"
fi


echo "------------------------------------------------"
echo "Stopping the Windows VM...."
su mimic -c "ssh $ROBOT-h1 'export DISPLAY=:0 && vboxmanage controlvm $ROBOT-win acpipowerbutton'"
echo "Stopping the robot...."
cobStartID=$(pgrep cob-start)
pgrep cob-start
if [ $? -eq 0 ]; then
  while [ -e /proc/$cobStartID ]; do 
        sleep 5
        #echo "(stopping the robot)...."
        echo "waiting for $cobStartID"
        #echo $cobStartID
  done
else
  echo "......(cob-start not running)....."
fi

#cleaning up roscore
su $USER -l -c "source /opt/ros/$DISTRO/setup.bash && rosnode cleanup"

rm -rf /tmp/robot.launch.pid

echo "....done!!                     "
echo "------------------------------------------------"
