#!/bin/bash
echo "------------------------------------------------"
echo "Stopping the Windows VM...."
su mimic -c "ssh myrobotname-h1 'export DISPLAY=:0 && vboxmanage controlvm myrobotname-win acpipowerbutton'"
echo "------------------------------------------------"
