#!/bin/bash
#
# Author: Mike Purvis <mpurvis@clearpathrobotics.com>
#         Copyright (c) 2013, Clearpath Robotics, Inc.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#    * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#    * Neither the name of Clearpath Robotics, Inc. nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL CLEARPATH ROBOTICS, INC. BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# Please send comments, questions, or patches to code@clearpathrobotics.com 
ROBOT=myrobotname
USER=myuser

if (ssh $USER@$ROBOT-t1 "tmux has-session -t 'statemachine' 2> /dev/null"); then
  echo "Attempting to stop statemachine"
  logger -p user.info "Attempting to stop statemachine"
  ssh $USER@$ROBOT-t1 "tmux send -t statemachine C-c"
  sleep 5
  ssh $USER@$ROBOT-t1 "tmux kill-session -t statemachine"
fi
if (su $USER -l -c "tmux has-session -t 'bringup' 2> /dev/null"); then
  echo "Attempting to stop robot.launch"
  logger -p user.info "Attempting to stop robot.launch"
  su $USER -l -c "tmux send -t bringup C-c"
  PID=$(cat /tmp/robot.launch.pid)
  while [ -e /proc/$PID ]; do sleep 0.1; done
  su $USER -l -c "tmux kill-session -t bringup"
fi


echo "------------------------------------------------"
echo "Stopping the Windows VM...."
su mimic -c "ssh $ROBOT-h1 'export DISPLAY=:0 && vboxmanage controlvm $ROBOT-win acpipowerbutton'"
echo "Stopping the robot...."
cobStartID=$(pgrep cob-start)
pgrep cob-start
if [ $? -eq 0 ]; then
  while [ -e /proc/$cobStartID ]; do 
        sleep 5
        #echo "(stopping the robot)...."
        echo "waiting for $cobStartID"
        #echo $cobStartID
  done
else
  echo "......(cob-start not running)....."
fi

#cleaning up roscore
su $USER -l -c "rosnode cleanup"

echo "....done!!                     "
echo "------------------------------------------------"

#rm -rf /tmp/robot.launch.pid
