#!/usr/bin/env bash

# Script for executing commands on all cob-pc's.
robot_name="${HOSTNAME//-b1}"

if [ "$HOSTNAME" != "$robot_name-b1" ]; then 
	echo "FATAL: CAN ONLY BE EXECUTED ON BASE PC($robot_name-b1), current host is $HOSTNAME"
	exit
fi


client_list="
$robot_name-t1
$robot_name-t2
$robot_name-t3
$robot_name-s1
$robot_name-h1
$robot_name-b1"

cob-stop-core

while /opt/ros/indigo/env.sh rostopic list > /dev/null; do
	sleep 1
done

for client in $client_list; do
	echo "-------------------------------------------"
	echo "Executing <<"shutdown">> on $client"
	echo "-------------------------------------------"
	echo ""
	ssh $client "sudo shutdown now -P 0"
	ret=${PIPESTATUS[0]}
	if [ $ret != 0 ] ; then
		echo "command return an error (error code: $ret), aborting..."
		#exit 1
	fi
	echo ""
done

