#!/bin/bash

set -e
client_list="CLIENT_LIST"
check_client_list="CHECK_LIST"

for i in $client_list; do
    while [ true ]
      do
        if ping -c1 $i &>/dev/null
          then
            echo "$i: ping ok"
            if ssh robot@$i '[ -d /u ]';
              then
                echo "$i: nfs set up"
                break
            else
                echo "$i: nfs not ready"
            fi
        else
            echo "$i: ping failed"
        fi
        sleep 1
    done
done

for i in $check_client_list; do
    while [ true ]
      do
        echo $(date)
        if ssh $i stat /tmp/check_done \> /dev/null 2\>\&1
          then
            echo "$i: cam_check done"
            break
          else
            echo "$i: cam_check pending"
        fi
      sleep 1
    done
done

# deal with mimic on -h1
if (echo "$client_list"  | fgrep -q "h1"); then

    # wait for mimic to be logged in into -h1
    echo "waiting for h1"
    while [ true ]; do
        echo "waiting for mimic to be logged in into h1"
        if [[ -n $( ssh h1 'who |grep ":0"| grep mimic') ]]; then
            echo "mimic logged in into h1"
            break
        fi
        sleep 1
    done

    if [ $(lsb_release -sc) == "trusty" ]; then
        # wait until screen is rotated
        echo "waiting for screen to rotate"
        sleep 10
    fi

else
    echo "skipping waiting for mimic to be logged in into h1 because no head pc available"
fi

echo "cob-command start"
/usr/sbin/cob-command start
