#!/bin/sh
#
echo "Write variables"

nvram set wan_hostname="robotname-bs"
nvram set wan_domain="robotname"
nvram set time_zone="Europe/Berlin"
nvram set telnetd_enable="1"
nvram set telnet_wanport="23"
nvram set sv_localdns="ipaddress.1"
nvram set sshd_wanport="22"
nvram set sshd_port="22"
nvram set sshd_passwd_auth="1"
nvram set sshd_forwarding="0"
nvram set sshd_enable="1"
nvram set sshd_authorized_keys=""
nvram set security_mode="disabled"
nvram set router_name="robotname-bs"
nvram set rc_startup="ifconfig ath0 down
ifconfig ath1 down
ifconfig ath2 down"
nvram set ntp_enable="0"
nvram set local_dns="0"
nvram set language="english"
nvram set lan_proto="static"
nvram set lan_netmask="255.255.255.0"
nvram set lan_lease="86400"
nvram set lan_ipaddr="ipaddress.254"
nvram set lan_gateway="ipaddress.1"
nvram set lan_domain="robotname"
nvram set expert_mode="1"
nvram set dnsmasq_enable="0"
nvram set dns_redirect="0"
nvram set dns_dnsmasq="0"
nvram set dns_crypt="0"
nvram set dmz_enable="0"
nvram set dlna_enable="0"
nvram set dhcpfwd_enable="0"
nvram set dhcp_dnsmasq="0"
nvram set dhcp6s_enable="0"
nvram set dhcp_domain="lan"
nvram set l2tp_use_dhcp="0"
nvram set ath2_wpa_psk="care-o-bot"
nvram set ath2_wep="disabled"
nvram set ath2_ssid="robotname-direct"
nvram set ath2_security_mode="psk2"
nvram set ath2_scanlist="default"
nvram set ath2_regulatory="1"
nvram set ath2_regdomain="GERMANY"
nvram set ath1_wpa_psk="care-o-bot"
nvram set ath1_wep="disabled"
nvram set ath1_ssid="robotname-direct"
nvram set ath1_security_mode="psk2"
nvram set ath1_scanlist="default"
nvram set ath1_regdomain="GERMANY"
nvram set ath0_wpa_psk="care-o-bot"
nvram set ath0_wpa_gtk_rekey="3600"
nvram set ath0_wep="disabled"
nvram set ath0_ssid="robotname-direct"
nvram set ath0_security_mode="psk2"
nvram set ath0_regdomain="GERMANY"

# Commit variables
echo "Save variables to nvram"
nvram commit
