name: CI

on: 
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # every Sunday at midnight
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          ssh-known-hosts: ''
      - uses: docker://koalaman/shellcheck-alpine
        with:
          # grep for executable files with bash or sh shebang, pipe through directory filter and file filter
          args: /bin/sh -c "shellcheck -x $(grep -rl '\#\!/bin/[bash,sh]' . | grep -v './manual_administrator\|.git' | grep -v './path/to/ignore\|./scripts/ddwrt/backupvars.sh')"
          # find details on specific errors under https://github.com/koalaman/shellcheck/wiki/<ERRORCODE>
