#!/bin/bash

set -e
ROBOT=myrobot
pcs="pc_list"
camera_client_list="checkPc_list"

for i in $pcs; do
    while [ true ]
      do
        if ping -c1 $i &>/dev/null
          then
            echo "$i: ping ok"
            if ssh robot@$i '[ -d /u ]';
              then
                echo "$i: nfs set up"
                break
            else
                echo "$i: nfs not ready"
            fi
        else
            echo "$i: ping failed"
        fi
        sleep 1
    done
done

for i in $camera_client_list; do
    while [ true ]
      do
        echo $(date)
        if ssh $i stat /tmp/check_done \> /dev/null 2\>\&1
          then
            echo "$i: cam_check done"
            break
          else
            echo "$i: cam_check pending"
        fi
      sleep 1
    done
done

# wait until screen is rotated
echo "waiting for screen to rotate"
sleep 10

function log() {
  logger -s -p user.$1 ${@:2}
}

echo "cob-command start"
/usr/sbin/cob-command start
