#!/bin/bash

set -e
ROBOT=myrobot
pcs="pc_list"
camera_client_list="checkPc_list"

for i in $pcs; do 
    until ping -c1 $i &>/dev/null; do
        echo $i not found
    done
    echo $i alive
done

for i in $camera_client_list; do 
    Check_cam=false
    while [[ !$Check_cam ]]
      do
        echo $(date)
        if ssh $i stat /tmp/check_done \> /dev/null 2\>\&1
          then
            echo "$i File exists"
            Check_cam=true
            break
          else
            echo "$i File still does not exist"
        fi
      sleep 1
    done
done

# fixes https://github.com/ipa320/msh/issues/887 to not hang on login screen but boot into desktop
while [ true ]
  do
    if [[ -n $( ssh $ROBOT-h1 'ps -ef | grep "gdm$"' ) ]]
    then
      echo "running"
      break
    fi
  sleep 1
done
echo "stopping"
ssh $ROBOT-h1 'sudo service gdm stop'
while [ true ]
  do
    if [[ -z $( ssh $ROBOT-h1 'ps -ef | grep "gdm$"' ) ]]
    then
      echo "stopped"
      break
    fi
  sleep 1
done
echo "restarting"
ssh $ROBOT-h1 'sudo service gdm restart'
while [ true ]
  do
    if [[ -n $( ssh $ROBOT-h1 'ps -ef | grep "gdm$"' ) ]]
    then
      echo "running"
      break
    fi
  sleep 1
done
sleep 10 # wait until screen is rotated
echo "slept"


function log() {
  logger -s -p user.$1 ${@:2}
}

/usr/sbin/cob-command start
