#!/bin/bash

set -e

# get pcs in local network
IP=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
pcs=$(nmap --unprivileged $IP-98 --system-dns | grep report | awk '{print $5}')

# define ASUS camera pcs
camera_client_list="
$ROBOT-t1
$ROBOT-t3
$ROBOT-s1"

for i in $pcs; do 
    Alive=False
    while [[ $Alive=False ]]
    do
        ping -qc 1 -w 3 $client > /dev/null
        if [ $? -ne 0 ] ; then
          Alive=False
          echo $i not found
        else
          Alive=True
          echo $i alive
          break
        fi
        sleep 1
    done
done

for i in $pcs_cameras; do 
    Check_cam=False
    while [[ $Check_cam=False ]]
      do
        if ssh $i stat /tmp/check_done \> /dev/null 2\>\&1
          then
            echo "File exists"
            Check_cam=True
            break
          else
            echo "File still does not exist"
        fi
      sleep 1
    done
done

function log() {
  logger -s -p user.$1 ${@:2}
}

/usr/sbin/cob-command start
